### ISSUE TITLE
Use htmx instead of json for RSVPs

### ISSUE THREAD

**Issue by m12r** [gograz/gograz-meetup#3]
Hi @zerok!

I'd like to change the RSVP endpoint to return a html fragment instead of json and get rid of the custom javascript in https://github.com/gograz/website and replace it with [htmx][]. htmx is small and well written javascript library which has zero dependencies and extends html tags in such a way that is enabling html to have modern features. htmx expects hypermedia (html fragments) in responses, instead of json.

In the website template it would look something like this:

```html
{{ if .Params.MeetupID }}
    <dl class="rsvps">
        <dt>Who's coming?</dt>
        <dd hx-get"https://api.gograz.org/meetup/{{ .Params.MeetupID }}/rsvps" hx-trigger="load delay:1s">
            Loading ...
        </dd>
    </dl>
{{ end }}
```

And in the API we would also have a template:

```html
{{ range . }}
    <a class="member" href="https://meetup.com/Graz-Open-Source-Meetup/members/{{ .ID }}" title="{{ .Name }}">
        {{ if .ThumbLink }}
             <img src="{{ .ThumbLink }}" alt="{{ .Name }}">
        {{ else }}
             <img src="/images/gopher.png" alt="{{ .Name }}">
        {{ end }}
    </a>
{{ else }}
    Be the first to RSVP!
{{ end }}
```

Would this be okay with you?

PS: I need an excuse to play around with htmx and do something useful, while doing so... 😉
PPS: I also prepare my talk for the next meetup!

[htmx]: https://htmx.org

**Comment by m12r** [comment]
FYI #2 is a preparation for the suggested change.

**Comment by zerok** [comment]
Can the backend somehow recognize HTMX requests and do content negotiation around that? Personally, I'd like to have both, HTMX and JSON, supported but otherwise, HTMX sounds like a nice solution for what gograz-meetup offers right now 😊

**Comment by m12r** [comment]
Content negotiation with htmx is easy, because htmx requests send a header `HX-Request: true`. Then we could serve either an html fragment or json.

**Comment by zerok** [comment]
Sorry for the long delay on this one 😢 I hope I will find for it this weekend.

**Comment by zerok** [comment]
@m12r https://github.com/gograz/gograz-meetup/pull/8 this should do it. WDYT?
